import React from "react";
import {loadFont} from "@remotion/google-fonts/NotoSansJP";
import {AbsoluteFill, Audio, OffthreadVideo, Sequence, interpolate, spring, staticFile, useCurrentFrame} from "remotion";
import {Episode} from "./lib/types";

const {fontFamily} = loadFont("normal", {weights: ["700", "900"]});
export const JUPITER_WALK_FPS = 30;
export const JUPITER_WALK_WIDTH = 1080;
export const JUPITER_WALK_HEIGHT = 1920;
const fps = JUPITER_WALK_FPS;
const f = (s: number) => Math.max(1, Math.ceil(s * fps));
const APPROACH = "movie/Spacecraft_descending_toward_Jup…_1080p_202609032302.mp4";
const DEEP = "movie/Capsule_descending_into_Jupiter'…_1080p_202609032303.mp4";

export const getJupiterWalkTimeline = (episode: Episode) => {
  const mins = [2.3, 2.6, 3.8, 3.3, 3.5, 3.7, 2.4, 2.2];
  const hookFrames = Math.max(f(episode.odaiDuration ?? 2), f(2));
  const answerFrames = episode.answers.map((a, i) => Math.max(f(a.duration ?? mins[i]), f(mins[i])));
  const answerStarts: number[] = [];
  let cursor = hookFrames;
  for (const d of answerFrames) { answerStarts.push(cursor); cursor += d; }
  const outroFrames = Math.max(f(episode.outroDuration ?? 4), f(4));
  return {hookFrames, answerFrames, answerStarts, outroFrom: cursor, outroFrames, totalFrames: cursor + outroFrames};
};

const C = {space: "#020812", navy: "#06182a", cyan: "#50e8ff", yellow: "#ffe36b", orange: "#ff993d", red: "#ff4e45", cream: "#f2d6aa"};
const VideoShade = () => <AbsoluteFill style={{background: "linear-gradient(180deg,rgba(1,5,12,.78),rgba(1,5,12,.02) 43%,rgba(1,5,12,.73) 100%)"}} />;
const Badge = ({concept = false}: {concept?: boolean}) => <><div style={{position:"absolute",zIndex:50,top:42,left:34,padding:"12px 20px 15px",border:"3px solid #fff",borderRadius:999,background:"linear-gradient(135deg,#263e68,#a25d2a)",color:"#fff",fontSize:25,fontWeight:900,lineHeight:1,boxShadow:"0 7px 0 #020812,0 16px 32px #0009"}}>宇宙の歩き方</div><div style={{position:"absolute",zIndex:50,top:47,right:32,padding:"10px 13px 12px",border:"2px solid #fff9",borderRadius:9,background:"#000b",color:"#fff",fontSize:18,fontWeight:700,lineHeight:1}}>{concept ? "AI再現・概念図" : "AIによる宇宙旅行再現"}</div></>;

const Headline = ({children, color="#fff", size=76, top=150}: {children:React.ReactNode;color?:string;size?:number;top?:number}) => {const frame=useCurrentFrame();const s=spring({frame,fps,config:{damping:8,stiffness:190,mass:.55}});return <div style={{position:"absolute",zIndex:45,top,left:28,right:28,textAlign:"center",color,fontSize:size,lineHeight:1.06,fontWeight:900,letterSpacing:-3,WebkitTextStroke:"7px #020812",paintOrder:"stroke fill",textShadow:"0 14px 34px #000",transform:`scale(${interpolate(s,[0,1],[1.2,1])})`}}>{children}</div>};
const Caption = ({children, accent=C.cyan}: {children:React.ReactNode;accent?:string}) => {const frame=useCurrentFrame();return <div style={{position:"absolute",zIndex:60,left:62,right:62,bottom:232,padding:"18px 22px 23px",borderTop:`8px solid ${accent}`,borderRadius:18,background:"rgba(2,8,16,.94)",boxShadow:"0 16px 42px #000d",color:"#fff",fontSize:43,lineHeight:1.22,fontWeight:900,textAlign:"center",opacity:interpolate(frame,[0,5],[0,1],{extrapolateRight:"clamp"})}}>{children}</div>};
const Footer = () => <div style={{position:"absolute",zIndex:25,left:38,bottom:181,color:"#cbd5df",fontSize:20,fontWeight:700}}>出典: NASA Jupiter Facts</div>;

const Hook = () => {const frame=useCurrentFrame();const shake=frame>34?Math.sin(frame*2.7)*7:0;return <AbsoluteFill style={{transform:`translateX(${shake}px)`}}><OffthreadVideo src={staticFile(APPROACH)} muted style={{width:"100%",height:"100%",objectFit:"cover"}}/><VideoShade/><Badge/><Headline size={72}>木星に着陸すると<br/><span style={{color:C.yellow,fontSize:112}}>人はどうなる？</span></Headline><div style={{position:"absolute",left:100,right:100,top:650,height:520,border:"5px solid #ffffff88",borderRadius:"50%",boxShadow:`0 0 ${30+frame}px ${C.cyan}55`}}/></AbsoluteFill>};
const NoGround = () => {const frame=useCurrentFrame();const alarm=interpolate(frame,[0,10,25,55],[0,1,.2,1],{extrapolateRight:"clamp"});return <AbsoluteFill><OffthreadVideo src={staticFile(APPROACH)} startFrom={38} muted style={{width:"100%",height:"100%",objectFit:"cover"}}/><VideoShade/><Badge/><Headline color={C.red} size={91}>待って！<br/><span style={{fontSize:118}}>地面がない！</span></Headline><div style={{position:"absolute",zIndex:40,left:100,right:100,top:700,height:480,border:`12px solid rgba(255,78,69,${alarm})`,borderRadius:35,boxShadow:`0 0 70px rgba(255,78,69,${alarm})`}}/><Caption accent={C.red}>待って！ 地面がありません！</Caption></AbsoluteFill>};
const EpisodeTitle = () => <AbsoluteFill><OffthreadVideo src={staticFile(APPROACH)} startFrom={82} muted style={{width:"100%",height:"100%",objectFit:"cover"}}/><VideoShade/><Badge/><div style={{position:"absolute",top:280,left:60,right:60,border:"7px solid #fff",borderRadius:36,background:"rgba(3,13,26,.78)",padding:"55px 25px 62px",textAlign:"center",boxShadow:"0 30px 80px #000c"}}><div style={{color:C.cream,fontSize:52,fontWeight:900}}>宇宙の歩き方</div><div style={{marginTop:20,color:"#fff",fontSize:91,fontWeight:900}}>第1回</div><div style={{color:C.yellow,fontSize:147,lineHeight:1,fontWeight:900}}>木 星</div></div><Caption>宇宙の歩き方。<br/>第1回、木星。</Caption></AbsoluteFill>;

const CloudBg = () => {const frame=useCurrentFrame();return <AbsoluteFill style={{background:`linear-gradient(180deg,#071326 0%,#43311f 22%,#a66b38 48%,#4d281b 72%,#140b0b 100%)`}}>{Array.from({length:11},(_,i)=><div key={i} style={{position:"absolute",left:-120+(i%3)*55,right:-120,top:230+i*145+((frame*(3+i%3))%145),height:90,borderRadius:"50%",background:i%3===0?"#e5c18c99":i%3===1?"#a6633588":"#f0d8af66",filter:"blur(17px)",transform:`skewX(${i%2?12:-10}deg)`}}/>)}</AbsoluteFill>};
const CapsuleIcon = ({top=600,scale=1,glow=false}: {top?:number;scale?:number;glow?:boolean}) => <div style={{position:"absolute",zIndex:25,top,left:"50%",width:190,height:245,transform:`translateX(-50%) scale(${scale})`,borderRadius:"48% 48% 38% 38%",background:"linear-gradient(90deg,#172332,#9eabb1 48%,#182330)",border:"7px solid #d7e1e5",boxShadow:glow?`0 0 65px ${C.orange},inset 0 0 40px ${C.orange}`:"0 20px 45px #000c"}}><div style={{position:"absolute",left:40,right:40,top:35,height:65,borderRadius:"50%",background:"#071221",border:`5px solid ${C.cyan}`}}/></div>;

const Search = () => {const frame=useCurrentFrame();const scan=(frame*14)%1050;return <AbsoluteFill><CloudBg/><Badge concept/><Headline size={70}>着陸地点を<br/><span style={{color:C.cyan,fontSize:94}}>検索中…</span></Headline><CapsuleIcon top={560} scale={.75}/><div style={{position:"absolute",zIndex:30,left:150,right:150,top:800+scan,height:12,borderRadius:"50%",background:C.cyan,boxShadow:`0 0 25px ${C.cyan},0 0 65px ${C.cyan}`}}/><div style={{position:"absolute",left:38,top:760,color:"#fff",fontSize:29,fontWeight:900}}>↓ 降下中</div><div style={{position:"absolute",right:38,top:760,color:C.yellow,fontSize:26,fontWeight:900}}>地面検出: ―</div><Footer/><Caption>降りても降りても、見えるのは雲。<br/>着陸地点は出ません。</Caption></AbsoluteFill>};
const NoSurface = () => {const frame=useCurrentFrame();const stamp=spring({frame:Math.max(0,frame-12),fps,config:{damping:7,stiffness:210}});return <AbsoluteFill><CloudBg/><Badge concept/><Headline size={65}>着陸地点<br/><span style={{color:C.yellow,fontSize:107}}>該当なし</span></Headline><div style={{position:"absolute",top:650,left:70,right:70,padding:"72px 30px",border:"7px solid #fff",borderRadius:34,background:"rgba(3,10,20,.83)",textAlign:"center",transform:`scale(${interpolate(stamp,[0,1],[1.5,1])}) rotate(${interpolate(stamp,[0,1],[-8,0])}deg)`,boxShadow:"0 30px 80px #000c"}}><div style={{color:"#fff",fontSize:49,fontWeight:900}}>木星には</div><div style={{color:C.red,fontSize:105,lineHeight:1.08,fontWeight:900}}>地表がない</div></div><Footer/><Caption accent={C.red}>木星には、本当の意味での<br/>地表がないからです。</Caption></AbsoluteFill>};

const Pressure = () => {const frame=useCurrentFrame();const ring=interpolate(frame,[0,105],[1.5,.62],{extrapolateRight:"clamp"});return <AbsoluteFill><OffthreadVideo src={staticFile(DEEP)} startFrom={0} muted style={{width:"100%",height:"100%",objectFit:"cover"}}/><VideoShade/><Badge/><Headline size={69}>深く進むほど<br/><span style={{color:C.orange,fontSize:100}}>圧力・温度 上昇</span></Headline>{[0,1,2].map(i=><div key={i} style={{position:"absolute",zIndex:35,left:"50%",top:650,width:520,height:520,border:`8px solid ${i===2?C.red:C.orange}`,borderRadius:"50%",opacity:.62-i*.13,transform:`translateX(-50%) scale(${ring+i*.22})`,boxShadow:`0 0 38px ${C.orange}`}}/>)}<Caption accent={C.orange}>さらに深く進むと、<br/>圧力と温度が上昇。</Caption></AbsoluteFill>};
const Destruction = () => {const frame=useCurrentFrame();const words=["押し潰す","溶かす","蒸発させる"];return <AbsoluteFill><OffthreadVideo src={staticFile(DEEP)} startFrom={80} muted style={{width:"100%",height:"100%",objectFit:"cover"}}/><VideoShade/><Badge/><Headline top={135} size={62}>地面へ着く前に<br/><span style={{color:C.red,fontSize:88}}>機体が耐えられない</span></Headline><div style={{position:"absolute",zIndex:40,top:610,left:55,right:55,display:"flex",flexDirection:"column",gap:18}}>{words.map((w,i)=>{const s=spring({frame:Math.max(0,frame-i*26),fps,config:{damping:7,stiffness:200}});return <div key={w} style={{padding:"22px 20px 27px",border:`5px solid ${i===2?"#fff":C.orange}`,borderRadius:22,background:i===2?C.red:"rgba(30,10,5,.83)",color:"#fff",fontSize:57,fontWeight:900,textAlign:"center",opacity:s,transform:`translateX(${interpolate(s,[0,1],[i%2?-180:180,0])}px)`}}>{w}</div>})}</div><Footer/><Caption accent={C.red}>宇宙船は押し潰され、<br/>溶け、蒸発します。</Caption></AbsoluteFill>};
const Question = () => <AbsoluteFill><OffthreadVideo src={staticFile(APPROACH)} startFrom={0} muted style={{width:"100%",height:"100%",objectFit:"cover"}}/><VideoShade/><Badge/><Headline top={320} size={73}>では、<br/><span style={{color:C.yellow,fontSize:105}}>どこに降りれば？</span></Headline><Caption accent={C.yellow}>では、どこに降りれば？</Caption></AbsoluteFill>;
const Return = () => {const frame=useCurrentFrame();const up=interpolate(frame,[0,66],[0,-330],{extrapolateRight:"clamp"});return <AbsoluteFill><CloudBg/><Badge concept/><div style={{transform:`translateY(${up}px)`}}><CapsuleIcon top={900} scale={.8}/></div><Headline top={315} size={72}>答え<br/><span style={{color:C.cyan,fontSize:103}}>降りずに帰ってください</span></Headline><Caption>降りずに帰ってください。</Caption></AbsoluteFill>};
const Outro = () => {const frame=useCurrentFrame();const hit=spring({frame:Math.max(0,frame-18),fps,config:{damping:7,stiffness:215}});const cta=spring({frame:Math.max(0,frame-55),fps,config:{damping:9,stiffness:175}});return <AbsoluteFill><OffthreadVideo src={staticFile(APPROACH)} startFrom={0} muted style={{width:"100%",height:"100%",objectFit:"cover",filter:"brightness(.42) saturate(1.3)"}}/><Badge/><div style={{position:"absolute",top:285,left:42,right:42,bottom:220,border:"8px solid #fff",borderRadius:43,background:"rgba(2,10,22,.84)",boxShadow:"0 32px 85px #000e",textAlign:"center"}}><div style={{marginTop:105,color:"#fff",fontSize:67,fontWeight:900}}>宇宙の歩き方なのに</div><div style={{marginTop:40,color:C.yellow,fontSize:102,lineHeight:1.05,fontWeight:900,letterSpacing:-5,WebkitTextStroke:"6px #fff",paintOrder:"stroke fill",textShadow:"0 13px 0 #74551a",transform:`scale(${interpolate(hit,[0,1],[1.35,1])})`}}>歩く場所<br/>ないんかい！</div><div style={{margin:"70px auto 0",width:330,height:200,backgroundImage:"radial-gradient(ellipse,#fff 0 36%,transparent 38%),radial-gradient(ellipse,#fff 0 35%,transparent 37%)",backgroundSize:"145px 190px",backgroundPosition:"10px 5px,180px 5px",backgroundRepeat:"no-repeat",opacity:interpolate(frame,[22,62],[1,0],{extrapolateRight:"clamp"}),transform:`translateY(${interpolate(frame,[20,62],[0,160],{extrapolateRight:"clamp"})}px)`}}/><div style={{position:"absolute",left:86,right:86,bottom:75,padding:"24px 10px 29px",border:"4px solid #fff",borderRadius:20,background:C.cyan,color:C.space,fontSize:41,fontWeight:900,opacity:cta,transform:`scale(${interpolate(cta,[0,1],[.82,1])})`}}>チャンネル登録もよろしく！</div></div></AbsoluteFill>};

const SceneAudio=({voice,effect,volume=.18}:{voice?:string;effect?:string;volume?:number})=><>{voice?<Audio src={staticFile(voice)}/>:null}{effect?<Audio src={staticFile(effect)} volume={volume}/>:null}</>;
export const JupiterWalkGuideShort: React.FC<{episode:Episode}> = ({episode}) => {const t=getJupiterWalkTimeline(episode);const scenes=[<NoGround/>,<EpisodeTitle/>,<Search/>,<NoSurface/>,<Pressure/>,<Destruction/>,<Question/>,<Return/>];return <AbsoluteFill style={{background:C.space,fontFamily:`${fontFamily},'Yu Gothic',sans-serif`}}><Audio src={staticFile(episode.bgm??"BGM/Lab Rocket Switch.mp3")} startFrom={30} volume={(frame)=>.085*interpolate(frame,[0,10,t.totalFrames-22,t.totalFrames],[0,1,1,0],{extrapolateRight:"clamp"})}/><Sequence from={0} durationInFrames={t.hookFrames}><Hook/><SceneAudio voice={episode.odaiAudioFile} effect="Effect/シャキーン1.mp3" volume={.14}/></Sequence>{episode.answers.map((a,i)=><Sequence key={a.id} from={t.answerStarts[i]} durationInFrames={t.answerFrames[i]}>{scenes[i]}<SceneAudio voice={a.audioFile} effect={i===0?"Effect/ショック2.mp3":i===3?"Effect/ドーン.mp3":i===5?"Effect/ビシッとツッコミ2.mp3":undefined} volume={i===3?.22:.15}/></Sequence>)}<Sequence from={t.outroFrom} durationInFrames={t.outroFrames}><Outro/><SceneAudio voice={episode.outroAudioFile} effect="Effect/ビシッとツッコミ1.mp3" volume={.28}/></Sequence></AbsoluteFill>};
