import React from "react";
import {loadFont} from "@remotion/google-fonts/NotoSansJP";
import {AbsoluteFill, Audio, OffthreadVideo, Sequence, interpolate, spring, staticFile, useCurrentFrame} from "remotion";
import {Episode} from "./lib/types";

const {fontFamily}=loadFont("normal",{weights:["700","900"]});
export const VENUS_WALK_FPS=30, VENUS_WALK_WIDTH=1080, VENUS_WALK_HEIGHT=1920;
const fps=VENUS_WALK_FPS;
const f=(s:number)=>Math.ceil(s*fps);
const DESCENT="movie/Capsule_descending_into_Venus_at…_202609042137.mp4";
const SURFACE="movie/Capsule_descending_over_Venus_su…_202609042134.mp4";
const C={space:"#120803",cream:"#fff1cf",cyan:"#65edff",yellow:"#ffe166",amber:"#ff9a3d",red:"#ff4c32",brown:"#492010"};

export const getVenusWalkTimeline=(episode:Episode)=>{
  const mins=[2.1,2.2,3.3,1.7,3.4,2.1,3.3,2.5,2.4,1.9];
  const hookFrames=Math.max(f(episode.odaiDuration??2),f(2));
  const answerFrames=episode.answers.map((a,i)=>Math.max(f(a.duration??mins[i]),f(mins[i])));
  const answerStarts:number[]=[]; let cursor=hookFrames;
  answerFrames.forEach(d=>{answerStarts.push(cursor);cursor+=d;});
  const outroFrames=Math.max(f(episode.outroDuration??4),f(4));
  return {hookFrames,answerFrames,answerStarts,outroFrom:cursor,outroFrames,totalFrames:cursor+outroFrames};
};

const Video=({src,startFrom=0,dark=.32}:{src:string;startFrom?:number;dark?:number})=><AbsoluteFill><OffthreadVideo src={staticFile(src)} startFrom={startFrom} muted style={{width:"100%",height:"100%",objectFit:"cover"}}/><AbsoluteFill style={{background:`linear-gradient(180deg,rgba(16,5,0,.76),rgba(16,5,0,${dark}) 45%,rgba(10,3,0,.78))`}}/></AbsoluteFill>;
const Badge=({concept=false}:{concept?:boolean})=><><div style={{position:"absolute",zIndex:60,top:40,left:32,padding:"12px 20px 15px",border:"3px solid #fff",borderRadius:999,background:"linear-gradient(135deg,#7b3c20,#d18a3d)",color:"#fff",fontSize:25,fontWeight:900,boxShadow:"0 7px 0 #160703,0 15px 30px #0009"}}>宇宙の歩き方</div><div style={{position:"absolute",zIndex:60,top:47,right:30,padding:"10px 13px 12px",border:"2px solid #fff9",borderRadius:9,background:"#160703dd",color:"#fff",fontSize:18,fontWeight:700}}>{concept?"AI再現・概念図":"AIによる宇宙旅行再現"}</div></>;
const Headline=({children,color="#fff",size=74,top=150}:{children:React.ReactNode;color?:string;size?:number;top?:number})=>{const frame=useCurrentFrame();const s=spring({frame,fps,config:{damping:8,stiffness:190,mass:.55}});return <div style={{position:"absolute",zIndex:50,top,left:28,right:28,textAlign:"center",color,fontSize:size,lineHeight:1.06,fontWeight:900,letterSpacing:-3,WebkitTextStroke:"7px #170704",paintOrder:"stroke fill",textShadow:"0 14px 34px #000",transform:`scale(${interpolate(s,[0,1],[1.18,1])})`}}>{children}</div>};
const Caption=({children,accent=C.amber}:{children:React.ReactNode;accent?:string})=>{const frame=useCurrentFrame();return <div style={{position:"absolute",zIndex:70,left:58,right:58,bottom:230,padding:"18px 20px 23px",borderTop:`8px solid ${accent}`,borderRadius:18,background:"rgba(18,7,2,.95)",boxShadow:"0 16px 42px #000d",color:"#fff",fontSize:42,lineHeight:1.22,fontWeight:900,textAlign:"center",opacity:interpolate(frame,[0,5],[0,1],{extrapolateRight:"clamp"})}}>{children}</div>};
const Footer=()=> <div style={{position:"absolute",zIndex:35,left:38,bottom:180,color:"#f2dcc6",fontSize:20,fontWeight:700}}>出典: NASA Venus Facts</div>;
const Planet=({left,color,label,hot=false}:{left:number;color:string;label:string;hot?:boolean})=>{const frame=useCurrentFrame();return <div style={{position:"absolute",left,top:650,width:310,textAlign:"center"}}><div style={{width:270,height:270,margin:"auto",borderRadius:"50%",background:`radial-gradient(circle at 32% 28%,#fff8,transparent 15%),${color}`,boxShadow:hot?`0 0 ${45+12*Math.sin(frame/4)}px ${C.red}`:"0 0 32px #65edff55",border:"5px solid #fff"}}/><div style={{marginTop:28,color:"#fff",fontSize:47,fontWeight:900}}>{label}</div></div>};
const Rings=({count=8}:{count?:number})=>{const frame=useCurrentFrame();return <>{Array.from({length:count},(_,i)=>{const p=(frame*7+i*55)%440;return <div key={i} style={{position:"absolute",zIndex:32,left:"50%",top:825,width:240+p,height:240+p,border:`${i?5:8}px solid ${i?C.amber:C.cyan}`,borderRadius:"50%",opacity:1-p/470,transform:"translate(-50%,-50%)",boxShadow:`0 0 20px ${C.red}88`}}/>})}</>};

const Hook=()=> <AbsoluteFill><Video src={DESCENT}/><Badge/><Headline size={70}>金星に降りたら<br/><span style={{color:C.yellow,fontSize:112}}>人はどうなる？</span></Headline><Caption>まもなく、金星に到着します。</Caption></AbsoluteFill>;
const Warning=()=>{const frame=useCurrentFrame();const pulse=1+.05*Math.sin(Math.min(frame,28)*Math.PI/7);return <AbsoluteFill><Video src={DESCENT} startFrom={46}/><Badge/><Headline color={C.red} size={91}>待って！<br/><span style={{fontSize:132}}>約467℃</span></Headline><div style={{position:"absolute",zIndex:42,top:570,left:95,right:95,padding:"45px",border:`10px solid ${C.red}`,borderRadius:32,background:"#4b1009dd",boxShadow:`0 0 80px ${C.red}`,textAlign:"center",transform:`scale(${pulse})`}}><div style={{color:C.cream,fontSize:38,fontWeight:900}}>地表温度</div><div style={{color:"#fff",fontSize:122,fontWeight:900}}>約467℃</div></div><Caption accent={C.red}>待って！ 外、約467度です！</Caption></AbsoluteFill>};
const Title=()=> <AbsoluteFill><Video src={DESCENT} startFrom={98}/><Badge/><div style={{position:"absolute",top:290,left:62,right:62,padding:"50px 20px 58px",border:"7px solid #fff",borderRadius:36,background:"#351306d9",textAlign:"center",boxShadow:"0 30px 80px #000c"}}><div style={{color:C.cream,fontSize:50,fontWeight:900}}>宇宙の歩き方</div><div style={{color:"#fff",fontSize:86,fontWeight:900}}>第2回</div><div style={{color:C.yellow,fontSize:150,lineHeight:1,fontWeight:900}}>金 星</div></div><Caption>宇宙の歩き方。第2回、金星。</Caption></AbsoluteFill>;
const Sisters=()=> <AbsoluteFill style={{background:"radial-gradient(circle at 50% 45%,#6f3518,#170804 70%)"}}><Badge concept/><Headline size={70}>大きさは<span style={{color:C.cyan}}>ほぼ同じ</span></Headline><Planet left={120} color="linear-gradient(145deg,#2776b9,#3bc58a)" label="地球"/><Planet left={650} color="linear-gradient(145deg,#f9d486,#b75d2c)" label="金星"/><Footer/><Caption>金星は、地球とほぼ同じ大きさの姉妹惑星。</Caption></AbsoluteFill>;
const Easy=()=> <AbsoluteFill><Video src={SURFACE}/><Badge/><Headline top={270} color={C.cyan} size={94}>旅行しやすそう<br/>なのだ♪</Headline><Caption accent={C.cyan}>旅行しやすそうなのだ。</Caption></AbsoluteFill>;
const Heat=()=>{const frame=useCurrentFrame();return <AbsoluteFill style={{transform:`translateX(${Math.sin(frame*2.3)*4}px)`}}><Video src={SURFACE} startFrom={35}/><Badge/><Headline color={C.red} size={72}>でも太陽系で<br/><span style={{fontSize:101}}>最も高温</span></Headline><div style={{position:"absolute",zIndex:40,top:610,left:90,right:90,padding:"32px 20px",border:`7px solid ${C.red}`,borderRadius:30,background:"#481006dd",color:"#fff",fontSize:104,fontWeight:900,textAlign:"center",boxShadow:`0 0 60px ${C.red}`}}>約467℃</div><Footer/><Caption accent={C.red}>ですが、地表は約467度。</Caption></AbsoluteFill>};
const Oven=()=> <AbsoluteFill><Video src={SURFACE} startFrom={92}/><Badge/><Headline top={270} color={C.yellow} size={82}>オーブンより<br/><span style={{fontSize:112}}>本気なのだ！</span></Headline><Caption accent={C.red}>オーブンより本気なのだ！</Caption></AbsoluteFill>;
const Pressure=()=> <AbsoluteFill style={{background:"radial-gradient(circle,#8b4825,#170804 68%)"}}><Badge concept/><Headline size={69}>金星の地表<br/><span style={{color:C.red,fontSize:108}}>気圧 約93倍</span></Headline><Rings/><div style={{position:"absolute",zIndex:40,top:710,left:"50%",width:145,height:190,transform:"translateX(-50%)",borderRadius:"48% 48% 38% 38%",background:"linear-gradient(90deg,#172332,#abb5b9,#182330)",border:"6px solid #fff"}}/><div style={{position:"absolute",zIndex:42,top:1110,left:160,right:160,padding:"17px",border:"3px solid #fff",borderRadius:15,background:"#170804d9",color:C.cream,fontSize:35,fontWeight:900,textAlign:"center"}}>水深 約930mに相当</div><Footer/><Caption accent={C.red}>気圧は、地球の約93倍。</Caption></AbsoluteFill>;
const Combo=()=> <AbsoluteFill><Video src={SURFACE} startFrom={130}/><Badge/><Headline top={235} size={72}>焼くのと潰すの<br/><span style={{color:C.red,fontSize:103}}>同時なのだ!?</span></Headline><div style={{position:"absolute",zIndex:40,top:670,left:65,right:65,display:"flex",gap:18}}>{["約467℃","約93倍"].map((x,i)=><div key={x} style={{flex:1,padding:"38px 8px",border:"6px solid #fff",borderRadius:25,background:i?"#8a2c18e8":"#bc481de8",color:"#fff",fontSize:55,fontWeight:900,textAlign:"center"}}>{x}</div>)}</div><Caption accent={C.red}>焼くのと潰すの、同時なのだ!?</Caption></AbsoluteFill>;
const Acid=()=>{const frame=useCurrentFrame();return <AbsoluteFill style={{background:"linear-gradient(#b97032,#71351c 47%,#241009)"}}><Badge concept/><Headline size={76}>さらに上空には<br/><span style={{color:C.yellow,fontSize:105}}>硫酸の雲</span></Headline>{Array.from({length:18},(_,i)=>{const y=(i*113+frame*5)%1000;return <div key={i} style={{position:"absolute",left:40+(i*137)%1000,top:430+y,width:18+(i%3)*8,height:30+(i%3)*12,borderRadius:"50%",background:C.cream,opacity:.8-y/1400,filter:"blur(1px)"}}/>})}<div style={{position:"absolute",left:0,right:0,bottom:0,height:520,background:"linear-gradient(transparent,#35150c)",clipPath:"polygon(0 65%,20% 42%,38% 61%,58% 35%,78% 57%,100% 44%,100% 100%,0 100%)"}}/><Footer/><Caption>さらに上空には、硫酸の雲。</Caption></AbsoluteFill>};
const Umbrella=()=> <AbsoluteFill><Video src={DESCENT} startFrom={110}/><Badge/><Headline top={270} color={C.yellow} size={84}>傘の問題じゃ<br/><span style={{fontSize:111}}>ないのだ！</span></Headline><Caption accent={C.yellow}>傘の問題じゃないのだ！</Caption></AbsoluteFill>;
const Outro=()=>{const frame=useCurrentFrame();const hit=spring({frame:Math.max(0,frame-12),fps,config:{damping:7,stiffness:210}});return <AbsoluteFill><Video src={SURFACE} startFrom={115} dark={.6}/><Badge/><div style={{position:"absolute",zIndex:45,top:275,left:42,right:42,bottom:215,border:"8px solid #fff",borderRadius:42,background:"#260d05e8",textAlign:"center",boxShadow:"0 30px 80px #000e"}}><div style={{marginTop:76,color:C.cream,fontSize:59,fontWeight:900}}>地球の姉妹なのに</div><div style={{marginTop:35,color:C.yellow,fontSize:92,lineHeight:1.05,fontWeight:900,letterSpacing:-5,WebkitTextStroke:"6px #fff",paintOrder:"stroke fill",transform:`scale(${interpolate(hit,[0,1],[1.35,1])})`}}>圧が強すぎる<br/>んかい！</div><div style={{margin:"58px 55px 0",padding:"25px 10px",border:`4px solid ${C.cyan}`,borderRadius:20,color:"#fff",fontSize:37,fontWeight:900}}>金星、降りてみたい？<br/><span style={{color:C.cyan,fontSize:30}}>行ってみたい ／ 上空からで十分</span></div><div style={{position:"absolute",left:70,right:70,bottom:62,padding:"22px 8px 27px",border:"4px solid #fff",borderRadius:20,background:C.yellow,color:C.brown,fontSize:39,fontWeight:900}}>チャンネル登録もよろしく！</div></div></AbsoluteFill>};

const SceneAudio=({voice,effect,volume=.16}:{voice?:string;effect?:string;volume?:number})=><>{voice?<Audio src={staticFile(voice)}/>:null}{effect?<Audio src={staticFile(effect)} volume={volume}/>:null}</>;
export const VenusWalkGuideShort:React.FC<{episode:Episode}>=({episode})=>{const t=getVenusWalkTimeline(episode);const scenes=[<Warning/>,<Title/>,<Sisters/>,<Easy/>,<Heat/>,<Oven/>,<Pressure/>,<Combo/>,<Acid/>,<Umbrella/>];return <AbsoluteFill style={{background:C.space,fontFamily:`${fontFamily},'Yu Gothic',sans-serif`}}><Audio src={staticFile(episode.bgm??"BGM/Lab Rocket Switch.mp3")} startFrom={30} volume={(frame)=>.085*interpolate(frame,[0,10,t.totalFrames-22,t.totalFrames],[0,1,1,0],{extrapolateRight:"clamp"})}/><Sequence durationInFrames={t.hookFrames}><Hook/><SceneAudio voice={episode.odaiAudioFile} effect="Effect/シャキーン1.mp3"/></Sequence>{episode.answers.map((a,i)=><Sequence key={a.id} from={t.answerStarts[i]} durationInFrames={t.answerFrames[i]}>{scenes[i]}<SceneAudio voice={a.audioFile} effect={i===0?"Effect/ショック2.mp3":i===4?"Effect/ドーン.mp3":i===6?"Effect/文字表示の衝撃音3.mp3":i===9?"Effect/ビシッとツッコミ2.mp3":undefined} volume={i===6?.22:.16}/></Sequence>)}<Sequence from={t.outroFrom} durationInFrames={t.outroFrames}><Outro/><SceneAudio voice={episode.outroAudioFile} effect="Effect/ビシッとツッコミ1.mp3" volume={.28}/></Sequence></AbsoluteFill>};
